<form id="footer-form" method="post" onsubmit="return validateForm()">
    <div class="footer-wraper">
        <div class="footer-left">
            <div class="footer-heading">
                Customer Care<br>
                <hr>
            </div>
            <ul class="footer links">
                <li class="nav item">
                    <a href="http://m2p.local/privacy-policy-cookie-restriction-mode/">FAQS</a>
                </li>
                <li class="nav item">
                    <a href="http://m2p.local/sales/guest/form/">THE STORY</a>
                </li>
                <li class="nav item">
                    <a href="http://m2p.local/catalogsearch/advanced/" data-action="advanced-search">STORE LOCATION</a>
                </li>
                <li class="nav item">
                    <a href="http://m2p.local/contact/">BLOG</a>
                    <li class="nav item">
                        <a href="http://m2p.local/contact/">CAREERS</a>
                    </li>
                    <li class="nav item">
                        <a href="http://m2p.local/contact/">TERMS OF USE</a>
                    </li>
                    <li class="nav item">
                        <a href="http://m2p.local/contact/">SHIPPING</a>
                    </li>
                </li>
            </ul>
        </div>
        <div class="footer-mid">
            <div class="footer-heading">
                About<br>
                <hr>
            </div>
            <ul class="footer links">
                <li class="nav item">
                    "We are an elite squad of digital commerce that empowers brands and their exposure to its customers. We are an agency with a purpose for delivering measurable results for our clients."</br>
                    "We develop personalized business solutions for your online business."
                </li>
            </ul>
        </div>
        <div class="footer-right">
             <div class="footer-heading">
                Newsletter</br>
                <hr>
            </div>
            <ul class="footer links">
                <li class="nav item">
                    <a href="http://m2p.local/privacy-policy-cookie-restriction-mode/">Poin our mailing list</a>
                </li>
                <li class="nav item">
                    <input type="text" class="footer-email" name="footer-email" placeholder="your@email"></br></br>
                    <button class="subscribe" type="submit">Subscribe</button>
                </li>
            </ul>
        </div>
    </div>
    <div class="after-footer">
        <div class="card">
            <img src='http://m2p.local/pub/media/slider/card.svg' alt="card">
        </div>
        <div class="master-card">
            <img src='http://m2p.local/pub/media/slider/master_card.svg' alt="master-card">
        </div>
        <div class="visa">
            <img src='http://m2p.local/pub/media/slider/visa.svg' alt="visa">
        </div>
    </br>
    <div class="fb">
        <i class="fab fa-facebook-f"></i>    
    </div>
    <div class="insta">
        <i class="fab fa-instagram"></i>
    </div>
    </br>
    © COPYRIGHT ORION CODERS 2019
    </div>
</form>
